
import { Product, ProductCategory, StockStatus } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Classic Corn Tortillas',
    description: 'Authentic, stone-ground corn tortillas, perfect for tacos, enchiladas, and more. Made fresh daily.',
    price: 3.50,
    size: '36 count',
    image: '/images/Classic_corn_tortillas.jpg',
    stockStatus: StockStatus.InStock,
    category: ProductCategory.Corn,
  },
  {
    id: 2,
    name: 'Blue Corn Tortillas',
    description: 'Nutty and flavorful tortillas made from organic blue corn. A beautiful and delicious addition to any meal.',
    price: 4.50,
    size: '24 count',
    image: '/images/Blue_corn_tortillas.jpg',
    stockStatus: StockStatus.InStock,
    category: ProductCategory.Corn,
  },
  {
    id: 3,
    name: 'Traditional Flour Tortillas',
    description: 'Soft, pliable flour tortillas, ideal for burritos, quesadillas, and wraps. A family favorite.',
    price: 4.00,
    size: '12 count (Large)',
    image: 'https://picsum.photos/seed/flourtortilla/400/400',
    stockStatus: StockStatus.InStock,
    category: ProductCategory.Flour,
  },
  {
    id: 4,
    name: 'Whole Wheat Flour Tortillas',
    description: 'A healthier option with the same great taste. Made with 100% whole wheat flour.',
    price: 4.50,
    size: '12 count (Large)',
    image: 'https://picsum.photos/seed/wheattortilla/400/400',
    stockStatus: StockStatus.OutOfStock,
    category: ProductCategory.Flour,
  },
  {
    id: 5,
    name: 'Salsa Roja',
    description: 'A classic roasted tomato and chili salsa with a medium heat level. The perfect pairing for our chips.',
    price: 5.00,
    size: '16 oz',
    image: 'https://picsum.photos/seed/salsaroja/400/400',
    stockStatus: StockStatus.InStock,
    category: ProductCategory.Salsas,
  },
  {
    id: 6,
    name: 'Salsa Verde',
    description: 'A tangy and bright salsa made from tomatillos, cilantro, and jalapeños. Mild and refreshing.',
    price: 5.00,
    size: '16 oz',
    image: 'https://picsum.photos/seed/salsaverde/400/400',
    stockStatus: StockStatus.InStock,
    category: ProductCategory.Salsas,
  },
  {
    id: 7,
    name: 'Horchata',
    description: 'A sweet and creamy traditional rice milk drink, flavored with cinnamon and vanilla.',
    price: 3.00,
    size: '20 oz',
    image: 'https://picsum.photos/seed/horchata/400/400',
    stockStatus: StockStatus.InStock,
    category: ProductCategory.Drinks,
  },
  {
    id: 8,
    name: 'Agua de Jamaica',
    description: 'A refreshing hibiscus iced tea, lightly sweetened and perfect for a warm day.',
    price: 3.00,
    size: '20 oz',
    image: 'https://picsum.photos/seed/jamaica/400/400',
    stockStatus: StockStatus.OutOfStock,
    category: ProductCategory.Drinks,
  },
];

export const NAV_LINKS = [
  { name: 'Home', path: '/' },
  { name: 'Products', path: '/products' },
  { name: 'About Us', path: '/about' },
  { name: 'Contact', path: '/contact' },
];
